### ISSUE TITLE
32 or 64 bit browser information wrong

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/nem-homepage#2]
When a person checks the FAQ about which browser they have in Chrome, it says that it will say if it is 32 or 64 bit.  That is wrong.  It only says if it is 64 bit.  If it is 32 bit it won't say anything.  

http://www.tech-recipes.com/rx/50195/how-do-i-know-if-i-am-using-google-chrome-32-bit-or-64-bit/

**Comment by crackerhead** [comment]
bit checking instructions have been removed altogether as they are no longer needed, closing issue, thanks!
